format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$c\
$golang\
$helm\
$lua\
$pulumi\
$python\
$rust\
$terraform\
$zig\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character
"""
right_format = "$kubernetes"
palette = "gruvbox_dark"
add_newline = true
command_timeout = 500
scan_timeout = 30

[palettes.gruvbox_dark]
color_aqua = "#689d6a"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_blue = "#458588"
color_fg0 = "#fbf1c7"
color_green = "#98971a"
color_orange = "#d65d0e"
color_purple = "#b16286"
color_red = "#cc241d"
color_yellow = "#d79921"

[directory]
format = "[ $path]($style)"
style = "fg:color_yellow bold"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~/Git/gitlab.ptsecurity.com/ptcs" = "…/ptcs"

[git_branch]
format = "[ $symbol $branch]($style)"
style = "fg:color_aqua bold"
symbol = ""

[git_commit]
format = "[( $hash$tag)]($style)"
style = "fg:color_green bold"

[git_status]
format = "[( $all_status$ahead_behind)]($style)"
style = "fg:color_red bold"

[c]
format = "[ $symbol( $version)]($style)"
style = "fg:color_yellow"
symbol = " "

[cmd_duration]
format = "[  $duration]($style)"
style = "bold fg:color_orange"

[golang]
format = "[ $symbol( $version)]($style)"
style = "fg:color_blue"
symbol = ""

[helm]
format = "[ $symbol( $version)]($style)"
style = "fg:color_blue"
symbol = "⎈"

[kubernetes]
disabled = false
format = "[$symbol $context( ($namespace)) ]($style)"
style = "fg:color_blue bold"
symbol = "⎈"

[python]
format = "[ $symbol( $version)]($style)"
style = "fg:color_green"
symbol = ""

[rust]
format = "[ $symbol( $version)]($style)"
style = "fg:color_orange"
symbol = ""
